name: 'github-action-devops-cloudformation-deployer'
description: 'Step to deploy cloudformation with GithubActions'
inputs:
  githubtoken:
    description: 'Github Token'
    required: true
  cfnparams:
    description: 'Parameters to Cloudformation Deployer'
    required: true
runs:
  using: "composite"
  steps:     
  - id: install-cloudformation-deployer-and-deploy-iac
    run: | 
      # Clone and deploy cloudformation-deployer library
      git clone https://${{ inputs.githubtoken }}:x-oauth-basic@github.com/cepsadigital/cloudformation-deployer.git ~/cloudformation-deployer
      mkdir -p /home/${USER}/.local/bin/
      sudo ln -s /home/${USER}/cloudformation-deployer/cloudformation_deploy.py /usr/bin/cloudformation-deployer
      python3 -m pip install --user -r ~/cloudformation-deployer/requirements.txt
      # Deploy iac
      cloudformation-deployer ${{ inputs.cfnparams }}
    shell: bash
